name: Build WiFi Printer EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Build Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pywin32 pystray Pillow qrcode pyinstaller

    - name: Build Portable Executable
      run: |
        pyinstaller --noconsole --onefile --name "WiFi_Printer_Server_BENOZIR" main_server.py

    - name: Publish Executable
      uses: actions/upload-artifact@v4
      with:
        name: WiFi_Printer_Server_BENOZIR_2026
        path: dist/WiFi_Printer_Server_BENOZIR.exe
